apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blogs-anavinfotech-in-tls
  namespace: blogs
spec:
  secretName: tls-secret
  dnsNames:
    - blogs.anavinfotech.in  # Replace with your domain
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

